### ISSUE TITLE
Replace <%= paketPath %>

### ISSUE THREAD

**Issue by reidev275** [reidev275/Fix#2]
some templates have a `paketPath` that should be replaced

https://github.com/fsprojects/generator-fsharp/blob/templates/fslabjournal/build.cmd#L7

**Comment by reidev275** [comment]
now that we have paket in fix I'm not sure that this is needed @Krzysztof-Cieslak am I correct in this thinking?

**Comment by Krzysztof-Cieslak** [comment]
I think it would be good to still support it for people preferring to use local paket installation, and just general compatibility
